package fr.si2m.rp.swift.orm;
// Generated 4 nov. 2013 15:49:58 by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * IbanExcludes generated by hbm2java
 */
public class IbanExcludes  implements java.io.Serializable {


     private int noInterne;
     private String cdIbanPaysIso;
     private String cdIbanNationalId;
     private String cdIbanBic;
     private short noIdBatch;
     private String cdActivite;
     private Date dtCreation;
     private Date hrCreation;
     private String niCreation;
     private Date dtModif;
     private Date hrModif;
     private String niModif;
     private Date dtAnnulation;
     private Date hrAnnulation;
     private String niAnnulation;

    public IbanExcludes() {
    }

	
    public IbanExcludes(int noInterne, String cdIbanPaysIso, String cdIbanNationalId, short noIdBatch, Date dtCreation, Date hrCreation, String niCreation) {
        this.noInterne = noInterne;
        this.cdIbanPaysIso = cdIbanPaysIso;
        this.cdIbanNationalId = cdIbanNationalId;
        this.noIdBatch = noIdBatch;
        this.dtCreation = dtCreation;
        this.hrCreation = hrCreation;
        this.niCreation = niCreation;
    }
    public IbanExcludes(int noInterne, String cdIbanPaysIso, String cdIbanNationalId, String cdIbanBic, short noIdBatch, String cdActivite, Date dtCreation, Date hrCreation, String niCreation, Date dtModif, Date hrModif, String niModif, Date dtAnnulation, Date hrAnnulation, String niAnnulation) {
       this.noInterne = noInterne;
       this.cdIbanPaysIso = cdIbanPaysIso;
       this.cdIbanNationalId = cdIbanNationalId;
       this.cdIbanBic = cdIbanBic;
       this.noIdBatch = noIdBatch;
       this.cdActivite = cdActivite;
       this.dtCreation = dtCreation;
       this.hrCreation = hrCreation;
       this.niCreation = niCreation;
       this.dtModif = dtModif;
       this.hrModif = hrModif;
       this.niModif = niModif;
       this.dtAnnulation = dtAnnulation;
       this.hrAnnulation = hrAnnulation;
       this.niAnnulation = niAnnulation;
    }
   
    public int getNoInterne() {
        return this.noInterne;
    }
    
    public void setNoInterne(int noInterne) {
        this.noInterne = noInterne;
    }
    public String getCdIbanPaysIso() {
        return this.cdIbanPaysIso;
    }
    
    public void setCdIbanPaysIso(String cdIbanPaysIso) {
        this.cdIbanPaysIso = cdIbanPaysIso;
    }
    public String getCdIbanNationalId() {
        return this.cdIbanNationalId;
    }
    
    public void setCdIbanNationalId(String cdIbanNationalId) {
        this.cdIbanNationalId = cdIbanNationalId;
    }
    public String getCdIbanBic() {
        return this.cdIbanBic;
    }
    
    public void setCdIbanBic(String cdIbanBic) {
        this.cdIbanBic = cdIbanBic;
    }
    public short getNoIdBatch() {
        return this.noIdBatch;
    }
    
    public void setNoIdBatch(short noIdBatch) {
        this.noIdBatch = noIdBatch;
    }
    public String getCdActivite() {
        return this.cdActivite;
    }
    
    public void setCdActivite(String cdActivite) {
        this.cdActivite = cdActivite;
    }
    public Date getDtCreation() {
        return this.dtCreation;
    }
    
    public void setDtCreation(Date dtCreation) {
        this.dtCreation = dtCreation;
    }
    public Date getHrCreation() {
        return this.hrCreation;
    }
    
    public void setHrCreation(Date hrCreation) {
        this.hrCreation = hrCreation;
    }
    public String getNiCreation() {
        return this.niCreation;
    }
    
    public void setNiCreation(String niCreation) {
        this.niCreation = niCreation;
    }
    public Date getDtModif() {
        return this.dtModif;
    }
    
    public void setDtModif(Date dtModif) {
        this.dtModif = dtModif;
    }
    public Date getHrModif() {
        return this.hrModif;
    }
    
    public void setHrModif(Date hrModif) {
        this.hrModif = hrModif;
    }
    public String getNiModif() {
        return this.niModif;
    }
    
    public void setNiModif(String niModif) {
        this.niModif = niModif;
    }
    public Date getDtAnnulation() {
        return this.dtAnnulation;
    }
    
    public void setDtAnnulation(Date dtAnnulation) {
        this.dtAnnulation = dtAnnulation;
    }
    public Date getHrAnnulation() {
        return this.hrAnnulation;
    }
    
    public void setHrAnnulation(Date hrAnnulation) {
        this.hrAnnulation = hrAnnulation;
    }
    public String getNiAnnulation() {
        return this.niAnnulation;
    }
    
    public void setNiAnnulation(String niAnnulation) {
        this.niAnnulation = niAnnulation;
    }




}


